pipeline:
  build:
    image: openjdk:8-jdk
    commands:
      - ./gradlew clean build
      - ./gradlew -Dsonar.host.url=http://sonarqube.target.com:9000 -Dsonar.login="be98043a2149d0b004a31e2486ed4a3681b34157" -Dsonar.forceAnalysis=true -Dsonar.verbose=true test sonarqube

  docker:
    image: plugins/docker:17.12
    secrets: [ docker_username, docker_password ]
    registry: docker.target.com
    repo: docker.target.com/dojo-bootcamp/dojoitem
    tag:
      - latest
      - "b${DRONE_BUILD_NUMBER}-${DRONE_COMMIT:0:8}"
    Dockerfile: Dockerfile


