pipeline:
  build:
    image: openjdk:8-jdk
    commands:
      - ./gradlew clean build
  docker:
    image: plugins/docker:17.12
    secrets: [ docker_username, docker_password ]
    registry: docker.target.com
    repo: docker.target.com/dojo-bootcamp/dojoitem
    tag: latest
    Dockerfile: Dockerfile


